chore: Restore MSRV to 1.85.0, for passing CI
This fixes the CI error:

https://github.com/maflcko/octocrab/actions/runs/24987243681/job/73163540500#step:6:243

```
error: rustc 1.94.1 is not supported by the following packages:
  octocrab@0.49.9 requires rustc 1.95.0
```